apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "1"
        memory: 1024Ki
      default:
        cpu: 1000m
        memory: 1024Gi
      min:
        cpu: 100m
        memory: 1024ki
      max:
        cpu: 1000m
        memory: 1024Gi
    - type: Pod
      min:
        cpu: 100m
        memory: 1024ki
      max:
        cpu: 1000m
        memory: 1024Gi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
