apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-depl
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args:
            ["--cpu", "2", "--vm", "1", "--vm-bytes", "1G", "--vm-hang", "1"]
          resources:
            requests:
              cpu: "1"
              memory: "1Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
