version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./redirect.conf
        target: /etc/nginx/conf.d/default.conf
