apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-example
  labels:
    app: nodeaffinity-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeaffinity-example
  template:
    metadata:
      labels:
        app: nodeaffinity-example
      name: nodeaffinity-example
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rank
                    operator: Lt
                    values:
                      - "5"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: rank
                    operator: Gt
                    values:
                      - "5"
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: "1"
              memory: "1Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
