apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-example
  labels:
    app: nodeaffinity-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeaffinity-example
  template:
    metadata:
      labels:
        app: nodeaffinity-example
      name: nodeaffinity-example
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rank
                    operator: Lt
                    values:
                      - "5"
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args:
            ["--cpu", "1", "--vm", "1", "--vm-bytes", "1G", "--vm-hang", "1"]
          resources:
            requests:
              cpu: "1"
              memory: "1Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
