apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodename-scheduler-example
  labels:
    app: nodename-scheduler-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodename-scheduler-example
  template:
    metadata:
      labels:
        app: nodename-scheduler-example
      name: nodename-scheduler-example
    spec:
      nodeName: minikube-m03
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args:
            ["--cpu", "2", "--vm", "1", "--vm-bytes", "1G", "--vm-hang", "1"]
          resources:
            requests:
              cpu: "1"
              memory: "1Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
