apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-server
  labels:
    app: ubuntu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-server
  template:
    metadata:
      labels:
        app: ubuntu-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rank
                    operator: Lt
                    values:
                      - "5"
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep", "136000"]
