name: issue comment

on:
  issues:
    type: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Gentle reminder:\n* Did you go through all of the troubleshooting steps outlined in README.md?"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
